<div class="page-header">
    <h1><?php eh($titulo) ?>
        <?php echo Html::linkAction('crear', 'Registrar Usuario', 'class="btn btn-info pull-right hidden-phone"') ?>
    </h1>
</div>
<div class="row">
    <div class="span10 offset1">
        <div id="res-form-ajax"><?php View::content() ?></div>
        <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla01" width="100%">
            <thead>
                <tr>
                    <th>MUNICIPIO</th><th>PARROQUIA</th><th>NOMBRES</th>
                    <th>CEDULA</th><th>TELEFONO</th><th>CONTROL</th>
                </tr>                
            </thead>
            <tbody>
                <?php foreach($results As $r): ?>
                <tr>
                    <td><?php echo $r->municipio; ?></td>
                    <td><?php echo $r->parroquia; ?></td>
                    <td><?php echo $r->nombres; ?></td>
                    <td><?php echo $r->cedula; ?></td>
                    <td><?php echo $r->telef1; ?>
                    <?php if(!empty($r->telef2)) ?>
                        - <?php echo $r->telef2; ?>
                    </td>
                    <td>
                        <?php echo Html::linkAction("view/$r->id","Ver Ficha"); ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php View::partial('script/DataTables',false,array('id'=>'tabla01')); ?>