<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <?php $img = Html::img('insajuv.png',"App Registro",array('style'=>'width: 80px;')); ?>
            <?php echo Html::link('',"$img App Registro",'class = brand'); ?>
            <div class="nav-collapse">
                <?php View::renderMenu(Menu::BACKEND) ?>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="text-transform: capitalize;">
                            <?php eh(Auth::get('nombres')) ?>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
