<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <?php $img = Html::img('insajuv.png',"App Registro",array('style'=>'width: 80px;')); ?>
            <?php echo Html::link('',"$img Sistema Becas",'class = brand'); ?>
            <div class="nav-collapse pull-right">
                <ul class="nav">
                    <li><?php echo Html::link('panel/index', 'Administración') ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>